ALTER TABLE "Media"
ALTER COLUMN "fileName" DROP NOT NULL;

ALTER TABLE "Media"
ADD COLUMN "publicId" TEXT;

ALTER TABLE "Media"
ADD COLUMN "resourceType" TEXT NOT NULL DEFAULT 'image';

ALTER TABLE "Media"
ALTER COLUMN "resourceType" DROP DEFAULT;

ALTER TABLE "Media"
ADD COLUMN "department" TEXT;

ALTER TABLE "Media"
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE "Media"
ALTER COLUMN "updatedAt" DROP DEFAULT;
