const ROLE_PERMISSION_MAP = {
  SUPER_ADMIN: [
    'CREATE_RESERVATION', 'VIEW_RESERVATION', 'UPDATE_RESERVATION', 'CANCEL_VEHICLE_RESERVATION', 'MANAGE_RESERVATION_PAYMENT',
    'VIEW_TRIP', 'VIEW_PAYMENT', 'VIEW_OCCUPANCY', 'SCAN_TICKET', 'VIEW_TICKET_SCAN',
    'MANAGE_USERS', 'VIEW_VEHICLE', 'CREATE_VEHICLE', 'UPDATE_VEHICLE', 'DELETE_VEHICLE', 'MANAGE_VEHICLE_MEDIA',
    'VIEW_VEHICLE_INQUIRY', 'CREATE_VEHICLE_INQUIRY', 'UPDATE_VEHICLE_INQUIRY', 'ASSIGN_VEHICLE_INQUIRY', 'CLOSE_VEHICLE_INQUIRY', 'MANAGE_VEHICLE_INQUIRY', 'MANAGE_VEHICLE_RESERVATION',
    'CREATE_CUSTOMER_REQUEST', 'VIEW_CUSTOMER_REQUEST', 'UPDATE_CUSTOMER_REQUEST', 'CREATE_QUOTE_REQUEST', 'VIEW_QUOTE_REQUEST', 'UPDATE_QUOTE_REQUEST',
    'CREATE_PROJECT', 'VIEW_PROJECT', 'UPDATE_PROJECT', 'DELETE_PROJECT', 'CREATE_PROJECT_UPDATE',
    'VIEW_USER', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER', 'VIEW_ROLE', 'CREATE_ROLE', 'UPDATE_ROLE', 'DELETE_ROLE',
    'VIEW_PERMISSION', 'CREATE_PERMISSION', 'UPDATE_PERMISSION', 'DELETE_PERMISSION', 'VIEW_DEPARTMENT', 'CREATE_DEPARTMENT', 'UPDATE_DEPARTMENT', 'DELETE_DEPARTMENT',
    'CREATE_PARCEL', 'VIEW_PARCEL', 'UPDATE_PARCEL', 'RECEIVE_PARCEL', 'CHANGE_PARCEL_STATUS', 'VERIFY_PARCEL_PAYMENT', 'VIEW_PARCEL_PAYMENT', 'COLLECT_PARCEL', 'VIEW_IDENTITY_DATA', 'PRINT_PARCEL_RECEIPT',
  ],
  SERVICE_ADMIN: [
    'CREATE_RESERVATION', 'VIEW_RESERVATION', 'UPDATE_RESERVATION', 'CANCEL_VEHICLE_RESERVATION', 'MANAGE_RESERVATION_PAYMENT',
    'VIEW_TRIP', 'VIEW_PAYMENT', 'VIEW_OCCUPANCY', 'SCAN_TICKET', 'VIEW_TICKET_SCAN',
    'VIEW_VEHICLE', 'CREATE_VEHICLE', 'UPDATE_VEHICLE', 'DELETE_VEHICLE', 'MANAGE_VEHICLE_MEDIA',
    'VIEW_VEHICLE_INQUIRY', 'CREATE_VEHICLE_INQUIRY', 'UPDATE_VEHICLE_INQUIRY', 'ASSIGN_VEHICLE_INQUIRY', 'CLOSE_VEHICLE_INQUIRY', 'MANAGE_VEHICLE_INQUIRY', 'MANAGE_VEHICLE_RESERVATION',
    'CREATE_CUSTOMER_REQUEST', 'VIEW_CUSTOMER_REQUEST', 'UPDATE_CUSTOMER_REQUEST', 'CREATE_QUOTE_REQUEST', 'VIEW_QUOTE_REQUEST', 'UPDATE_QUOTE_REQUEST',
    'CREATE_PROJECT', 'VIEW_PROJECT', 'UPDATE_PROJECT', 'DELETE_PROJECT', 'CREATE_PROJECT_UPDATE',
    'VIEW_USER', 'CREATE_USER', 'UPDATE_USER', 'DELETE_USER',
    'CREATE_PARCEL', 'VIEW_PARCEL', 'UPDATE_PARCEL', 'RECEIVE_PARCEL', 'CHANGE_PARCEL_STATUS', 'VERIFY_PARCEL_PAYMENT', 'VIEW_PARCEL_PAYMENT', 'COLLECT_PARCEL', 'VIEW_IDENTITY_DATA', 'PRINT_PARCEL_RECEIPT',
  ],
  MANAGER: [
    'VIEW_RESERVATION', 'VIEW_TRIP', 'VIEW_PAYMENT', 'VIEW_OCCUPANCY', 'VIEW_TICKET_SCAN', 'VIEW_USER',
    'CREATE_PARCEL', 'VIEW_PARCEL', 'UPDATE_PARCEL', 'RECEIVE_PARCEL', 'CHANGE_PARCEL_STATUS', 'VERIFY_PARCEL_PAYMENT', 'VIEW_PARCEL_PAYMENT', 'COLLECT_PARCEL', 'VIEW_IDENTITY_DATA', 'PRINT_PARCEL_RECEIPT',
  ],
  AGENT: [
    'CREATE_RESERVATION', 'VIEW_RESERVATION', 'UPDATE_RESERVATION', 'MANAGE_RESERVATION_PAYMENT',
    'VIEW_TRIP', 'VIEW_PAYMENT', 'SCAN_TICKET', 'VIEW_TICKET_SCAN',
    'VIEW_VEHICLE', 'VIEW_VEHICLE_INQUIRY', 'CREATE_VEHICLE_INQUIRY', 'UPDATE_VEHICLE_INQUIRY',
    'VIEW_CUSTOMER_REQUEST', 'UPDATE_CUSTOMER_REQUEST', 'VIEW_QUOTE_REQUEST',
    'CREATE_PARCEL', 'VIEW_PARCEL', 'RECEIVE_PARCEL', 'CHANGE_PARCEL_STATUS', 'COLLECT_PARCEL', 'PRINT_PARCEL_RECEIPT',
  ],
};

const ROLE_DEPARTMENT_COMPATIBILITY = {
  SUPER_ADMIN: ['VANGUARD_COACH', 'CONSTRUCTION', 'AUTO_SALES'],
  SERVICE_ADMIN: ['VANGUARD_COACH', 'CONSTRUCTION', 'AUTO_SALES'],
  MANAGER: ['VANGUARD_COACH'],
  AGENT: ['VANGUARD_COACH'],
};

const normalizeRoleName = (roleName) => {
  const value = typeof roleName === 'string' ? roleName.trim().toUpperCase() : '';
  if (Object.prototype.hasOwnProperty.call(ROLE_PERMISSION_MAP, value)) {
    return value;
  }
  return null;
};

const isRoleDepartmentCompatible = (roleName, departmentType) => {
  const normalizedRole = normalizeRoleName(roleName);
  if (!normalizedRole) return false;
  const normalizedDepartment = typeof departmentType === 'string' ? departmentType.trim().toUpperCase() : '';
  return ROLE_DEPARTMENT_COMPATIBILITY[normalizedRole].includes(normalizedDepartment);
};

const getExpectedRolePermissions = (roleName) => {
  const normalizedRole = normalizeRoleName(roleName);
  if (!normalizedRole) return [];
  return [...ROLE_PERMISSION_MAP[normalizedRole]];
};

module.exports = {
  ROLE_PERMISSION_MAP,
  ROLE_DEPARTMENT_COMPATIBILITY,
  normalizeRoleName,
  isRoleDepartmentCompatible,
  getExpectedRolePermissions,
};
